name: Deploy to Cloudflare Pages

on:
  push:
  workflow_dispatch:
  schedule:
    # 毎日午前 0 時に実行する
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Generate markdowns
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_CONTENTS_DB_ID: ${{ secrets.NOTION_CONTENTS_DB_ID }}
          NOTION_POSTS_DB_ID: ${{ secrets.NOTION_POSTS_DB_ID }}
          NOTION_TALKS_DB_ID: ${{ secrets.NOTION_TALKS_DB_ID }}
          IMAGE_WORKER_AUTH_TOKEN: ${{ secrets.IMAGE_WORKER_AUTH_TOKEN }}
          IMAGE_WORKER_BASE_URL: ${{ secrets.IMAGE_WORKER_BASE_URL }}
          R2_PUBLIC_BASE_URL: ${{ secrets.R2_PUBLIC_BASE_URL }}
        run: |
          bun i
          bun run generate
        working-directory: ./tools/notion-content

      - name: Build
        run: |
          bun i
          bun run build
        working-directory: .

      - name: Publish to Cloudflare Pages
        id: publish_to_cloudflare_pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kosukesaigusa
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          wranglerVersion: '3'

      - name: Add publish URL as commit status
        uses: actions/github-script@v6
        with:
          script: |
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: 'Cloudflare Pages',
              description: 'Cloudflare Pages deployment',
              state: 'success',
              sha,
              target_url: "${{ steps.publish_to_cloudflare_pages.outputs.url }}",
            });
